config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#home'
  get 'stimulus', to: "pages#stimulus"
  get 'about', to: 'pages#about'
  # resources :articles, only: [:show]
  # resources :articles, only: [:show, :index, :new, :create, :edit, :update, :others, :delete, :destroy]
  resources :articles

  get 'signup', to: 'users#new'
  # post 'users', to: 'users#create'
  # resources :users, except: [:new]
  resources :users

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title, presence: true, 
    length: { minimum: 5, maximum: 100 }
  validates :description, presence: true,     
    length: { minimum: 5, maximum: 300 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  # , length: {minimum: 3, maximum:25 }
  validates_uniqueness_of :name
  validates_length_of :name, {minimum: 3, maximum: 25}

  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase}
  # any
  has_many :articles, dependent: :destroy
  validates :username, presence: true, 
      uniqueness: { case_sensitive: false }, 
      length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
      uniqueness: { case_sensitive: false }, 
      length: { maximum: 105 },
      format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  end


  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # when we put it here (instead of application_helper), all controllers will have current_user helper, not just view.
  def current_user
    # if we already have a current user, return it, otherwise we make a hit to db to get it.
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    # an older way to use if condition
    # if session[:user_id]
    #   User.find(session[:id])
  end

  def logged_in?
    # return true of false based on the current_user
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform this action"
      redirect_to login_path
    end
  end

  # make current_user to our views as well.
  helper_method :current_user, :logged_in?

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  # except show and index, all actions needs require_user.
  before_action :require_user, except: [:show, :index]
  # order matters! require_same_user has to go AFTER require_user (or what?)
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    # debug
    # byebug
  end

  def index
    # @articles = Article.all
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def create
    # byebug
    # render plain: params[:article].inspect
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article created successfully"
      # redirect_to article_path(@article)
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
    # byebug
  end
  
  def update
    # byebug
    
    if @article.update(article_params)
      flash[:notice] = "Article updated successfully"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def haha
    byebug
    render plain: "Haha"
  end

  def delete
  end


  def destroy
    @article.destroy
    flash[:notice] = "Article deleted successfully"
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if (current_user != @article.user) && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article."
      redirect_to @article
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created"
      redirect_to @category
    else
      render 'new'
    end
  end

  def index
    # @categories = Category.all
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name was successfully updated"
      redirect_to @category
    else
      render 'edit'
    end
  end


  private 

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? and current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def stimulus
  end

  def home
    redirect_to articles_path if logged_in?
    # render 'home'
  end

  def about
    # render 'about'
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    # byebug
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Sign the user in and redirect to the user's show page.
      session[:user_id] = user.id
      flash[:notice] = "#{user.username} logged in succesfully."
      # sign_in user
      redirect_to user
    else
      # Create an error message and re-render the signin form.
      # flash now
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    flash[:notice] = "logged out"
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)

  end

  def index
    # @users = User.all
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
    # return "hello"
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account has been successfully updated."
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    # byebug
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "#{@user.username} you have successfully signed up. Welcome to the blog."
      redirect_to articles_path
    else
      render :new
    end
  end

  def destroy
    puts "destroy user: #{@user.username}" 
    @user.destroy
    # for admin deleting other users without logging itself out.
    if (@user == current_user)
      session[:user_id] = nil
    end
    flash[:notice] = "#{@user.username} deleted!"
    redirect_to articles_path
  end

  private
  
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if (current_user != @user) && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account."
      redirect_to @user
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  # get the gravatar.
  def gravatar_for(user, options = { size: 80 } )
    hash = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "http://gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded mx-auto d-block shadow")
  end

end

app/views/articles/_article.html.erb
  <div class="container">
    <% @articles.each do |article| %>
      <div class="row justify-content-md-center ">
        <div class="col-8 mt-4">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
              by <%= link_to article.user.username, user_path(article.user) if article.user%>
            </div>
            <% if article.categories.any? %>
              <div class="mt-2">
                <%= render article.categories %>
              </div>
            <% end %>

            <div class="card-body">
              <h5 class="card-title">
              <%= link_to article.title, article_path(article), class: "text-success" %>
              </h5>

              <p class="card-text">
              <%= truncate(article.description, length:50) %>  
              </p>

              <%= link_to 'View', article_path(article), class: "btn btn-outline-success" %>
              
              <% if logged_in? && (current_user.admin? || article.user == current_user) %>
                <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-info" %>
                  
                <%= link_to 'Delete', article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
              <% end %>

            </div>

            <div class="card-footer text-muted">
              <small>Created <%= time_ago_in_words(article.created_at) %> ago, updated <%= time_ago_in_words(article.updated_at) %> </small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <div class="text-center mb-3">
      <%= link_to 'Create a New Article', new_article_path %>
    </div>
  </div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center ">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
    
      <%= form_with(model: @article, class:"shadow p-3 mb-5 bg-info rounded", local: true ) do |f| %>
        <div class="form-group row ">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :category, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.collection_select(:category_ids, Category.all, :id, :name, {:prompt => "Please select a category from the list below(can be empty)"}, {:multiple => true, size: 3, class: "custom-select shadow rounded" }) %>
          </div>

        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>

    <div class="mb-3">
      <%= link_to "[ Cancel and return to articles listing ]", articles_path, class: "text-info" %>
    </div>

  </div>
</div>

app/views/articles/edit.html.erb
<div id="page-content">
  <h1 class="text-center mt-4" >Edit page</h1>
  <%= render 'form' %>
</div>

app/views/articles/index.html.erb
  <h1 class="text-center mt-4" >Articles listing</h1>

  <div class="flickr_pagination">
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
  </div>

  <%= render 'article' %>

  <div class="flickr_pagination mb-4">
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
  </div>

  <%# <%= render 'article', obj: @articles %> 

app/views/articles/new.html.erb
<div id="page-content">
  <h1 class="text-center mt-4" >Create new article</h1>
  <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div id="page-content">
  <h2 class="text-center mt-4" > <%=@article.title %> </h2>

  <div class="container">
    <div class="row justify-content-md-center ">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            by <%= link_to @article.user.username, user_path(@article.user) if @article.user %>
            <%= link_to gravatar_for(@article.user), user_path(@article.user) if @article.user %>
            <% if @article.categories.any? %>
              <div class="mt-2">
                <%= render @article.categories %>
              </div>
            <% end %>
          </div>
          <div class="card-body">
            <div class="card-text text-left">
            <%= simple_format(@article.description ) %>  
            </div>

            <% if logged_in? && (current_user.admin? || @article.user == current_user) %>

              <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-info" %>
              
              <%= link_to 'Delete', article_path(@article), class: "btn btn-outline-danger", method: :delete , data:  {confirm: "Are you sure?"} %>

            <% end %>

          </div>

          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(@article.created_at) %> ago, updated <%= time_ago_in_words(@article.updated_at) %> </small>
          </div>
        </div>
      </div>
  </div>

</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class:"badge badge-pill badge-info mr-1" %>

app/views/categories/_form.html.erb
      <%= render 'shared/errors', obj: @category %>
      <%= form_with(model: @category, class:"shadow p-3 mb-5 bg-info rounded", local: true ) do |f| %>
        <div class="form-group row ">
          <%= f.label :name, "Category name", class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a category name" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4" >Edit category</h1>

<div class="container">
  <div class="row justify-content-center ">
    <div class="col-10">
      <%= render 'form' %>
    </div>

    <div class="mb-3">
      <%= link_to "[ Cancel and return to category ]", category_path(@category), class: "text-info" %>
    </div>

  </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4" >Categories</h1>

<div class="flickr_pagination">
  <div class="page_info">
    <%= page_entries_info @categories %>
  </div>
  <%= will_paginate @categories, :container => false %>
</div>

<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center ">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title">
            <%= link_to category.name, category_path(category) %>
            </h5>
            <p class="card-text">
              <%= pluralize(category.articles.count, "article")  %>
            </p>
          </div>

          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(category.created_at) %> ago, updated <%= time_ago_in_words(category.updated_at) %> </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination">
  <div class="page_info">
    <%= page_entries_info @categories %>
  </div>
  <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4" >Create new category</h1>

<div class="container">
  <div class="row justify-content-center ">
    <div class="col-10">
      <%= render 'shared/errors', obj: @category %>
      <%= form_with(model: @category, class:"shadow p-3 mb-5 bg-info rounded", local: true ) do |f| %>
        <div class="form-group row ">
          <%= f.label :name, "Category name", class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a category name" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>

    <div class="mb-3">
      <%= link_to "[ Cancel and return to articles listing ]", articles_path, class: "text-info" %>
    </div>

  </div>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
<div class="text-center mt-4">
  <%= link_to 'Edit category name', edit_category_url(@category), class: "btn btn-outline-info" %>
</div>
<% end %>

<div class="flickr_pagination">
  <div class="page_info">
    <%= page_entries_info @articles %>
  </div>
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination">
  <div class="page_info">
    <%= page_entries_info @articles %>
  </div>
  <%= will_paginate @articles, :container => false %>
</div>

app/views/layouts/_footer.html.erb
  <footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
    <small>Copyright &copy; <%= link_to "sunpochin", "https://linkedin.com/in/sunpochin", class: "text-white" %> </small><br>
    <small>Github repo  <%= link_to "github", "https://github.com/sunpochin/ruby-on-rails-alpha-blog", class: "text-white" %> </small>
    </div>
  </footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do | name, msg | %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%# <a class="navbar-brand" id="logo" href="#">Pochin's Blog</a> %>
  <%= link_to "柏青 rails blog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%# <a class="nav-link" href="#">Link</a> %>
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? %>
            <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
          <% end %>
          <%= link_to "View articles", articles_path, class: "dropdown-item" %>

          <%# <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a> %>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? && current_user.admin? %>
            <%= link_to "Create new category", new_category_url, class: "dropdown-item" %>
          <% end %>
          <%= link_to "View categories", categories_path, class: "dropdown-item" %>

        </div>
      </li>


      <li class="nav-item">
      </li>

      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Delete your profile", user_path(current_user), method: "delete", data:{ confirm: "Are you sure to delete account?"}, class: "dropdown-item text-danger" %>
          </div>
        </li>
      <% end %>

      <% if logged_in? %>
      <li class="nav-item">
        <%= link_to current_user.username, user_path(current_user), class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Log out", logout_path, method: :delete, class: "nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Log in", login_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign up", signup_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
    <%# <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pochin's Rails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>


</html>

app/views/pages/home.html.erb
<div id="page-content">

  <div class="container" id="home-container">
    <div class="jumbotron text-center text-white">
      <h1 class="display-4">Pochin's rails blog</h1>
      <p class="lead">This is my Ruby on Rails demo.</p>
      <hr class="my-4">

      <p class="lead">
        <%# <a class="btn btn-success btn-lg" href="#" role="button">Sign up!</a> %>
      <% if !logged_in? %>
        <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg" %>
      <% end %>
      </p>
    </div>
  </div>

</div>

app/views/pages/stimulus.html.erb
<div class="contrainer text-center">
  <%= content_tag :div, nil, data: {controller: "hello"} do %>
    <h1 data-target="hello.heading">hello page</h1>
    <h1 data-target="hello.haha">haha block</h1>

    <div class="btn btn-primary" data-action="click->hello#greet">Say Hello</div>

  <% end %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevents the <%= obj.class.name.downcase %> from being saved</h4>
    
    <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center ">
    <div class="col-10">

      <%= render 'shared/errors', obj: @user %>
    
      <%= form_with(model: @user, class:"shadow p-3 mb-5 bg-info rounded", local: true ) do |f| %>
        <div class="form-group row ">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Enter your password" %>
          </div>
        </div>


        <div class="form-group row justify-content-center">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light btn-lg") %>
        </div>
      <% end %>
    </div>

    <div class="mb-3">
      <%= link_to "[ Cancel and return to articles listing ]", articles_path, class: "text-info" %>
    </div>

  </div>
</div>

app/views/users/edit.html.erb
<div id="page-content">
  <h1 class="text-center mt-4" >Edit your profile</h1>
  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<h1 class="text-center mt-4" >Bloggers listing</h1>

  <div class="flickr_pagination">
    <div class="page_info">
      <%= page_entries_info @users %>
    </div>
    <%= will_paginate @users, :container => false %>
  </div>

  <div class="container">
    <% @users.each do | user | %>
      <div class="row justify-content-md-center ">
        <div class="col-8 mt-4">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
              <%= link_to user.username, user_path(user) %>
            </div>
            <div class="card-body">
              <h5 class="card-title">
              <%= link_to gravatar_for(user, size: 150), user %>
              </h5>
              <p class="card-text">
              <%= pluralize(user.articles.count, "article") %>  
              </p>
              <%= link_to "View profile", user, class: "btn btn-outline-success" %>

              <% if logged_in? %> 
                <% if user == current_user %> 
                  <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
                <% end %>
                <% if current_user.admin? %>
                  <%= link_to "Delete user", user_path(user), method: "delete", data:{ confirm: "Are you sure to delete this user #{user.username}?"}, class: "btn btn-outline-info text-danger" %>
                <% end %>
              <% end %>

            </div>

            <div class="card-footer text-muted">
              <small>Joined <%= time_ago_in_words(user.created_at) %> ago </small>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <div class="flickr_pagination mb-4">
      <div class="page_info">
        <%= page_entries_info @users %>
      </div>
      <%= will_paginate @users, :container => false %>
    </div>

  </div>

app/views/users/new.html.erb
<h1 class="text-center mt-4" >Sign up!</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4" ><%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size: 200 %>

<% if logged_in? && @user == current_user %>
  <div class="text-center mt-4">
    <%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-outline-info" %>
  </div>
<% end %>
<h3 class="text-center mt-4">Articles</h3>

<div class="flickr_pagination">
  <div class="page_info">
    <%= page_entries_info @articles %>
  </div>
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination mb-4">
  <div class="page_info">
    <%= page_entries_info @articles %>
  </div>
  <%= will_paginate @articles, :container => false %>
</div>


<%# render 'articles/article', obj: @user.articles %> 